services:
  composer:
    build:
      context: .
      target: custom_composer
    tty: true
    volumes:
      - .:/app
    networks:
      - mon-network

  symfony:
    build:
      context: .
      target: custom_symfony
    tty: true
    volumes:
      - .:/app
    environment:
      - APP_ENV=dev
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - composer
    networks:
      - mon-network

networks:
  mon-network:
    name: postgres_network
    external: true
